/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyecto.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test     
    public void testContadorElements() {
        App contador = new App(new int[]{1,2,3,4,5,6,7});
        assertEquals(7, contador.contadorElements());
    }

    @Test
    public void testContadorElementsBuit(){
        App contadorBuit = new App(new int[]{});
        assertEquals(0, contadorBuit.contadorElements());
    }

    @Test
    public void testRetornarPrimer(){
        App retornarPrimer = new App(new int[]{1,2,3,4,5,6,7});
        assertEquals(1, retornarPrimer.retornarPrimer());
    }

    @Test 
    public void testRetornarPrimerBuit(){
        App retornarPrimerBuit = new App(new int[]{});
        assertEquals(0, retornarPrimerBuit.retornarPrimer());
    }

    @Test
    public void testRetornarDarrer(){
        App retornarDarrer = new App(new int[]{1,2,3,4,5,6,7});
        assertEquals(7, retornarDarrer.retornarDarrer());
    }

    @Test
    public void testRetornarDarrerBuit(){
        App retornarDarrerBuit = new App(new int[]{});
        assertEquals(0, retornarDarrerBuit.retornarDarrer());
    }

    @Test
    public void testRetornaTercer(){
        App retornarTercer = new App(new int[]{1,2,3,4,5,6,7});
        assertEquals(3, retornarTercer.retornarTercer());
    }

    @Test
    public void testRetornaTercerBuit(){
        App retornarTercerBuit = new App(new int[]{});
        assertEquals(0, retornarTercerBuit.retornarTercer());
    }

    @Test
    public void testRetornaTercerMenor(){
        App retornarTercerMenor = new App(new int[]{1,2});
        assertEquals(0, retornarTercerMenor.retornarTercer());
    }

    @Test
    public void testSumarElements(){
        App sumarElements = new App(new int[]{-1,2,-3,-4,5,6,7});
        assertEquals(12, sumarElements.sumarElements());
    }

    @Test
    public void testMitjanaElements(){
        App MitjanaElements = new App(new int[]{-1,2,3,4,5,-6,7});
        assertEquals(2.0, MitjanaElements.mitjanaElements());
    }

}
