A = input ("Introduzca el nombre del alumno : ")
B = input ("Introduzca el apellido paterno : ")
C = input ("Introduzca el apellido materno : ")
D = input ("Introduzca el curso : ")
E = input ("Introduzca el color preferido : ")
F = input ("Introduzca la pelicula favorita : ")
print ("El alumno", A , B , C , "cursa ", D ," , su color favorito es " , E , " y su pelicula favorita es " , F)
