/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyecto.gradle;

public class App {
    private int[] arrayints;

    public App(int[] arrayints){
        this.arrayints = arrayints;
    }

    public int contadorElements(){
        if(arrayints != null){
            return arrayints.length;
        }else{
            return 0;
        }
    }
    
    public int retornarPrimer() {
        if (arrayints.length > 0) {
            return arrayints[0];
        } else {
            return 0;
        }
    }
    
    public int retornarDarrer() {
        if (arrayints.length > 0) {
            return arrayints[arrayints.length - 1];
        } else {
            return 0;
        }
    }
    
    public int retornarTercer() {
        if (arrayints.length >= 3) {
            return arrayints[2];
        } else {
            return 0;
        }
    }

    public int sumarElements(){
        int suma = 0;
        for (int numero : arrayints) {
            suma += numero;
        }
        return suma;
    }
    
    public double mitjanaElements() {
        if (arrayints.length > 0) {
            return (double) sumarElements() / arrayints.length;
        } else {
            return 0;
        }
    }
}
