A = int(input("¿Cuanto vale A? : "))
B = int(input ("¿Cuanto vale B? : "))
print ("Suma total = " , A+B)
print("Resta total = " , A-B)
print("Producto total = " , A*B)
print("Division total = " , A/B)
